# Generated by Django 5.2.7 on 2025-11-03 23:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_mecanico_zonatrabajo_ordentrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=1)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos (Inventario)',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('procedimientos', models.TextField(verbose_name='Procedimientos Realizados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='gestion.mecanico')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='gestion.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Bitácora de Trabajo',
                'verbose_name_plural': 'Bitácoras de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='BitacoraRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('bitacora', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='gestion.bitacora')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.repuesto')),
            ],
            options={
                'unique_together': {('bitacora', 'repuesto')},
            },
        ),
    ]
