# Generated by Django 5.2.7 on 2025-11-04 00:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_mecanico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='orden',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='gestion.ordentrabajo'),
        ),
    ]
